version: '3'

services:
  api:
    container_name: awesomemory_backend
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '4040:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL_FOR_DOCKER}
    volumes:
      - type: bind
        source: .
        target: /api
      - awesomemory-backend-node-modules:/api/node_modules
    command: [sh, -c, npx prisma migrate dev --name init && npx prisma db seed && yarn start:dev]
    networks:
      - awesomemory-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: awesomemory_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - awesomemory-network

volumes:
  awesomemory-backend-node-modules:
  db-store:

networks:
  awesomemory-network:
